services:
  dnsmasq:
    image: ghcr.io/mrohne/dnsmasq:latest
    container_name: dnsmasq
    environment:
      DNS1: "1.0.0.1"
      DNS2: "1.1.1.1"
    ports:
      - ${HOSTIP}:53:53/udp
      - ${HOSTIP}:53:53/tcp
    cap_add:
      - NET_ADMIN
    restart: always
